# Generated by Django 3.1.4 on 2021-02-06 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siteweb', '0003_utilisateur_telephone'),
    ]

    operations = [
        migrations.AddField(
            model_name='annonce',
            name='plat',
            field=models.CharField(max_length=150, null=True),
        ),
    ]
