# Generated by Django 3.1.4 on 2021-02-06 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siteweb', '0004_annonce_plat'),
    ]

    operations = [
        migrations.AddField(
            model_name='utilisateur',
            name='password',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
